/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:09a44275-a604-43d5-977a-62586f49d060",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L2DJNXweD",
    "aws_user_pools_web_client_id": "vk00kps8814qivhcuf777f57l",
    "oauth": {
        "domain": "sociallogingmail54644b29-54644b29-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
